#set( $symbol_pound = '#' )
#set( $symbol_dollar = '$' )
#set( $symbol_escape = '\' )
${symbol_pound} ${symbol_pound} config file version
apiVersion: 1

 ${symbol_pound} list of datasources to insert/update depending
 ${symbol_pound} on what's available in the datbase
datasources:
 - name: Prometheus
   type: prometheus
   access: proxy
   orgId: 1
   url: http://prometheus:9090
   version: 1
   editable: true