#set( $symbol_pound = '#' )
#set( $symbol_dollar = '$' )
#set( $symbol_escape = '\' )
apiVersion: v1
kind: Service
metadata:
  name: {{ template "bip-${artifactNameLowerCase}.fullname" . }}
  labels:
    app: {{ template "bip-${artifactNameLowerCase}.name" . }}
    chart: {{ template "bip-${artifactNameLowerCase}.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: {{ template "bip-${artifactNameLowerCase}.name" . }}
    release: {{ .Release.Name }}
