#set( $symbol_pound = '#' )
#set( $symbol_dollar = '$' )
#set( $symbol_escape = '\' )
${symbol_pound} Default values for bip-${artifactNameLowerCase}.
${symbol_pound} This is a YAML-formatted file.
${symbol_pound} Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: 172.30.1.1:5000/${artifactNameLowerCase}-spring-boot/bip-${artifactNameLowerCase}
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8080

ingress:
  enabled: true
  annotations: {}
    ${symbol_pound} kubernetes.io/ingress.class: nginx
    ${symbol_pound} kubernetes.io/tls-acme: "true"
  path: /
  hosts:
    - bip-${artifactNameLowerCase}-spring-boot.192.168.64.2.nip.io
  tls: []
  ${symbol_pound}  - secretName: chart-example-tls
  ${symbol_pound}    hosts:
  ${symbol_pound}      - chart-example.local

resources: {}
  ${symbol_pound} We usually recommend not to specify default resources and to leave this as a conscious
  ${symbol_pound} choice for the user. This also increases chances charts run on environments with little
  ${symbol_pound} resources, such as Minikube. If you do want to specify resources, uncomment the following
  ${symbol_pound} lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  ${symbol_pound} limits:
  ${symbol_pound}  cpu: 100m
  ${symbol_pound}  memory: 128Mi
  ${symbol_pound} requests:
  ${symbol_pound}  cpu: 100m
  ${symbol_pound}  memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}
